### ISSUE TITLE
Wrong visual example - Technical Writing

### ISSUE THREAD

**Issue by jeremyhaas** [USDA-FSA/fsa-design-system#106]
## Description

Guides / Content / Technical and Interface Writing / Guidelines / Code
In the context of the use of backticks, the second image shown seems as though should have been the code snippet example, instead of showing the stylized text.

## Steps to reproduce the issue

1. Please confirm that it seems to be an improper example, and inconsistent with other example patterns
1. If the source of the issue is with the 18F branch, please submit a pull request with their repo

**Comment by francisrupert** [comment]
Reassigning from @brianmillsUX to @francisrupert
