### ISSUE TITLE
Documentation: Alerts

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#110]
Document guidelines for **Alerts** component, https://github.com/USDA-FSA/fsa-style/issues/142

- [x] Drafting
- [x] Drafted

#117 

![image](https://cloud.githubusercontent.com/assets/1165933/23412512/620b98b4-fd9b-11e6-8a7e-c383684db10f.png)

**Comment by bignamehere** [comment]
Added Documentation for Alerts
