### ISSUE TITLE
Documentation: fsa-field

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#118]
- [x] Drafting
- [x] Drafted

for #117 

![image](https://cloud.githubusercontent.com/assets/1165933/23412297/bcc295c4-fd9a-11e6-8f2c-3c9956f09b57.png)

**Comment by bignamehere** [comment]
Completed documentation for [FSA Style #144](https://github.com/USDA-FSA/fsa-style/issues/144)
