### ISSUE TITLE
Footer's "Notices" URL

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#132]
### Where
http://usda-fsa.github.io/fsa-design-system/guides/applications/footer

### What
URL column for "Agency Guidelines > Notices" has extraneouscontent, specifically `" target="_blank`

### Screenshot
![image](https://user-images.githubusercontent.com/1165933/32745468-74b6a866-c878-11e7-9f18-64c9861791ad.png)

**Comment by bignamehere** [comment]
fixed and closing
