### ISSUE TITLE
Grunt Build Issue related to DS SCSS files

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-design-system#133]
There is currently a bug that happens on my system that affects the Watch and Build process when updating SCSS files. The flow files were updated to try and test the Watch process, and failed to build and update the fsa-design-system.css file in _site directory.

**Comment by bignamehere** [comment]
@francisrupert 

when you get a chance to take a look at this, let me know what you find.

**Comment by francisrupert** [comment]
@bignamehere,

Interesting, I couldn't reproduce it, it works fine for me. _Although_, I didn't get the SASS maps error in console either. So maybe there's something to that.

The beacon of hope is that it does it fine the first build, but fails at _watch_.

**_Extreme_ options** if you're at wit's end:
1. Run `npm i` in case there's some outdated dependency.
1. If that doesn't do it... reinstall **all** deps: 
    * backup current `node_modules` folder (e.g. rename to `node_modules@11-15-2017` or something)
    * and then `npm i` to get a shiny new set of deps.
1. If that doesn't do it... re-checkout entire repo: 
    * rename the entire *project* directory (e.g. `fsa-design-system@11-15-2017`) 
    * and `clone` repo. 
    * **NOTE:** any _local_ branches you have that you never pushed to origin will only be in that backup (`fsa-design-system@11-15-2017`). Consider pushing them to origin if you're worried (can always prune them later).

**Comment by bignamehere** [comment]
The Issue seemed to resolve itself when I restarted my machine. Who knows.....

**Comment by francisrupert** [comment]
Not so extreme a solution.
