### ISSUE TITLE
Update fsa-style dep to 2.1.1

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#145]
...once https://github.com/USDA-FSA/fsa-style/issues/203 is resolved and published.

- [x] Update `package.json` 
- [x] Update [Getting Started](https://github.com/USDA-FSA/fsa-design-system/blob/gh-pages/getting-started/index.md) reference to `2.1.1`
- [ ] Publish

**Comment by francisrupert** [comment]
USDA-FSA/fsa-style#203 has been completed and this issue can be addressed.

**Comment by bignamehere** [comment]
closing as per 7e8e0e0
