### ISSUE TITLE
Form Validation incorrect "prompt" screenshot

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#155]
Replace the below example with Growl `fsa-growl--centered` variation.

**Example:** On [PCP > Review](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/master/workflow_review.html), click on "Complete Review".

![image](https://user-images.githubusercontent.com/1165933/37363575-42d5ceb0-26c6-11e8-9f82-326fa50ee988.png)

**Comment by bignamehere** [comment]
completed as per 943d378
