### ISSUE TITLE
508 - Update Telephone related Documentation

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-design-system#162]
The current implementation of an anchor tag with a tel attribute could cause some assistive devices to perform or read the content in unintended ways. Based on research, a tel attribute combined with a specific aria-label would provide the appropriate solution. 

[Proposed Solution Article](http://thatdevgirl.com/blog/accessibility-phone-number-formatting)

here is the proposed solution code:

`<a href="tel:+8005551234" aria-label="FSA Telephone Number. 1. 800. 5 5 5. 1 2 3 4." target="_blank">1-800-555-1234</a>`

The aria-label should speak the telephone number in a more natural way, and not as a mathematical equation. Proposed solution sent to 508 team to open a dialogue about how to handle.

**Comment by francisrupert** [comment]
Good catch. Fascinating, and new to me. Can just picture the screen reader's voice reading `8005551234` as "_Eight Billion..._" or `800-555-1234` _"Eight hundred minus five hundred and..."_

**Comment by bignamehere** [comment]
Still exploring this one, as the 508 team believes the current implementation (not my proposed solution) is optimal. Need to do more research or look into a free screen reader plugin to test our content.

**Comment by bignamehere** [comment]
After testing using the ChromeVox browser plugin, the proposed option allowed for a better overall User Experience by speaking the aria-label that provided appropriate context for who you would be calling. The number spoken alone, does not serve the User well.
