### ISSUE TITLE
Stepped Control: JavaScript Considerations

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#189]
@bignamehere,

The Guidelines for Stepped Control are nicely done, however its "JavaScript Considerations" section has the Modal's JS content.

![image](https://user-images.githubusercontent.com/1165933/42032670-ed0c22bc-7a9f-11e8-9eb7-1f90ec7c475c.png)

**Comment by bignamehere** [comment]
Whoops... fixed now. :)
