### ISSUE TITLE
Draft "Should I..." to "Get Started"

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#233]
### Summary

A common question from FPAC clients:

> "When should [app_name] use the Design System?"

### Task

* Author a draft that quickly summarizes a few scenarios under which they **can/should/must/don't** use the Design System, and to what degree.
* Answer the question with a brief guide, likely integrated in [Getting Started](http://usda-fsa.github.io/fsa-design-system/getting-started/)

@francisrupert's gut response: start by **reframing** the question as

> "How shall an FPAC digital product *use* or *follow* the Design System?**"

_Use_ and _Follow_ are two different things, as alluded to in below pre-draft.

### Pre-draft dump:

:green_book: **Yes** to… new applications are being created.

:green_book: **Yes** to… existing legacy applications are being completely replaced/redeveloped.

:closed_book: **No** to… existing legacy applications are expected to convert to using the Design System.
* (See the below “Possibly”)

:orange_book: **Probably** to… existing legacy applications are looking for a significant overhaul. 
* This is a few steps removed from the above “completely replaced.”
* What criteria is used to determine “overhaul” requires discussion, weighed against benefit, and priority.

:notebook: **Maybe** to… existing legacy applications have major new features added (or even removed). 
* Sort of similar to the above “Probably.”

:green_book: **Possibly** to… existing legacy applications wish to utilize aspects of the Design System. 
* Top-down decision carefully discussed and prioritized.
* May not necessarily be adding/removing features. 
* For example, could be solely about as reskinning to be generally cohesive to the Design System (color, typography, spacing). 
* May likely involve not using most (or any) of the Design System’s CSS Framework (`fsa-style`); rather, involves referencing the Design System to apply the visual style, e.g. "let's just align to the Typography system."
* Requires a UI skill set and ability to balance UI and front-end decisions.

**Comment by bignamehere** [comment]
@francisrupert am going to start on this, since the rest of 1.14.2 release seems to need more clarification or it looks like you have already put work into the Issues.

**Comment by francisrupert** [comment]
@bignamehere Awesome. 

Definitely take my initial notes (Yes, No, Maybe, Probably, etc) as a rough starting point, though don’t have to be beholden to that format – it was just my gut instincts spilled out to get the thoughts down. 

We should draft it out iteratively and see where it takes us. I’ve also been thinking it might even lead us to reframing the “Getting Started” section – a natural evolution if it comes to that.

**Comment by bignamehere** [comment]
@francisrupert I added the "mini guide", and kept the same format, because I believe it helps to define the idea of "well, it depends." as an answer, with follow up criteria. There might be some outliers that we can come up with and add, but I believe most of what you stated (with slight updates) works well. Should this be added to release/1.14.2 or just keep as an issue branch for inclusion in a different release?

**Comment by francisrupert** [comment]
@bignamehere,

This is great. I wonder if this can be made more scannable as a `<table>`. Go ahead and explore how that might work - naturally using Markdown's table generation. I don't know it'd be all that much better, but warrants exploration.

And yes, after we have this nicely done (even if MVP-like), you can chuck it on `release/1.14.2` branch.
