### ISSUE TITLE
Create Date Picker Component Documentation Page

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-design-system#242]
## Description

A new Date Picker component has been developed for FSA Style, and needs to be documented.

Examples & Resource needed:

- [x] Components Page Icon
- [x] Default Example
- [x] Block Example
- [x] Field Example
- [x] Upper and Lower Date Limits
- [x] Disabled Example
- [x] Static / On Page Example
- [x] Static Disabled Form Field

Configurations:
- [x] How the Today Button functions and its purpose
- [x] How to disable specific days
- [x] Status Format variations
- [x] Set Range Low
- [x] Set Range High
- [ ] Set Disabled Dates

**Comment by francisrupert** [comment]
@bignamehere General FYI, I triaged this Issue back to Project [Design System: 2.3.0 / 1.12.0](https://github.com/orgs/USDA-FSA/projects/8), while the pushed out Date Picker Issues had already been in [Project Design System: 2.3.x / 1.12.x](https://github.com/orgs/USDA-FSA/projects/9). Same for Milestones.

**Comment by bignamehere** [comment]
@francisrupert I was experiencing some heavy JavaScript related lag when opening the Calendar, and after debugging and diagnosis, it seems the `accesslint.js` is causing a 15 second delay when paired with the datepicker. I commented out the script in `foot.scripts.dev.html`, and the delay went away.

**Comment by francisrupert** [comment]
@bignamehere,

Yeah, I'd experienced that too on a few other things. This note card, [projects/6#card-18777805](https://github.com/orgs/USDA-FSA/projects/6#card-18777805), quietly spoke to it on earlier boards.

**Comment by bignamehere** [comment]
@francisrupert 

didn't see that note... but good to know it wasn't just related to the datepicker.

**Comment by bignamehere** [comment]
@francisrupert  I have updated the Design System with the documentation for the Date Picker. I went with what I believe are the basic features that teams might request. gh-pages-dev is updated on the repo if you want to take a look. I plan on posting to gh-pages in the next day or so, so let me know if you see any discrepancies.

**Comment by francisrupert** [comment]
@bignamehere, this great! I’ll probably merge in a few minor tweaks, but this is definitely ready for prime time.

**Comment by francisrupert** [comment]
@bignamehere,

Pull down `gh-pages-dev` and review the four core commits amending this issue for minor tweaks: 

f14a1ad, 4c93123, e31db75, 3425cc7

**Comment by bignamehere** [comment]
@francisrupert I will pull down and merge, but what are your thoughts on the "Form Fields" vs "Form Field" comment I posted?
