### ISSUE TITLE
Doc Usage: Switch

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#293]
### Background

* [Switch Component](http://usda-fsa.github.io/fsa-design-system/components/switch/) was made available in `fsa-style@2.4.0`, via https://github.com/USDA-FSA/fsa-style/issues/153
* Currently has MVP level of documentation (via #270).

### Task

- [x] Documentation Research
- [x] Variations
- [x] **Usage** 
- [x] Accessibility implications
- [x] JavaScript implications
- [x] Related Resources

### Documentation Notes 

**Switch** and **Checkbox** are both technically an `input[type=checkbox]`, though **visually** and **behaviorally** different. They share functions but for a different **UI context**.

#### Bottom Line

* `switch` = Think of a light switch: toggle it and get immediate result.
* `checkbox` = Requires confirming action (i.e. submit button).

#### Labeling

* Both are technically **Binary**, it's either checked or it isn't (e.g. on/off, yes/no, true/false), therefore labeling guidelines for both types is pretty much identical.
* Do **not** label each state of a Switch, its accompanying label already implies its value (on/off, yes/no, true/false). Labeling the opposing states would be redundant.
  * [screenshot of a **no-no** example](https://cloud.githubusercontent.com/assets/1165933/20802511/e2665ca4-b7b1-11e6-80bb-ae0ddc9af824.png).

#### Behavior

**Immediacy** is a good differentiator:
* `switch` = **Instantaneously** activates a _state_.
* `checkbox` = Merely denotes a _selection_ (in queue) that **will not take until submitted**.

**Comment by bignamehere** [comment]
closing and adding to release 1.14.2
