### ISSUE TITLE
Doc Usage: Splash

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#295]
### Background

* [Splash Component](http://usda-fsa.github.io/fsa-design-system/components/splash/) was made available in `fsa-style@2.4.0`, via https://github.com/USDA-FSA/fsa-style/issues/358
* Currently has MVP level of documentation (via #279).

### Task

- [x] Documentation Research
- [x] Variations
- [x] **Usage** 
- [x] Accessibility implications
- [x] Related Resources

**Comment by bignamehere** [comment]
Adding quick fix of word redundancy to this issue...

Modal Page has redundant word "When its content content or features..."

removing with this issue.

**Comment by bignamehere** [comment]
@francisrupert it doesn't look like JavaScript implications are needed for the Splash component, but let me know if that is not the case.

**Comment by bignamehere** [comment]
@francisrupert please review "issue/295" branch and confirm ready to push to prod

https://github.com/USDA-FSA/fsa-design-system/tree/issue/295

**Comment by francisrupert** [comment]
> @francisrupert it doesn't look like JavaScript implications are needed for the Splash component, but let me know if that is not the case.

Yeah, that's about right. That was put in there more because it uses the **Progress** component (#294) which definitely has JS implications. So basically, the documentation for **Splash** (#295) should acknowledge and cross-reference that relationship.

Therefore, since Progress effectively is a **dependency** let's make sure documentation for Progress (#294) is drafted in concert with this one.

> @francisrupert please review "issue/295" branch and confirm ready to push to prod

First, great work on those updates! Let's collect your `fsa-design-system` work onto a single branch using the same pattern for previous releases; for this one would be **`release/1.14.2`**. Once those are all done, we'll move to `gh-pages-dev` and test before I publish to `gh-pages`.

I'll take care of that publish process on #298.

**Comment by bignamehere** [comment]
@francisrupert have some questions, so will ping you offline.

**Comment by bignamehere** [comment]
added to release branch 1.14.2
