### ISSUE TITLE
Doc Usage: Timeline

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#296]
### Background

* [Timeline Component](http://usda-fsa.github.io/fsa-design-system/components/timeline/) was made available in `fsa-style@2.4.0`, via https://github.com/USDA-FSA/fsa-style/issues/382, https://github.com/USDA-FSA/fsa-style/issues/383.
* Currently has MVP level of documentation (via #272).

### Task

- [x] Documentation Research
- [x] Variations
- [x] **Usage** 
- [x] Accessibility implications
- [ ] JavaScript implications
- [x] Related Resources

**Comment by bignamehere** [comment]
@francisrupert can individual "variants" be used alone or should they always be placed within a sequenced timeline? I can see the need to utilize a single Comment variant within an application. Thoughts recommending the usage of single variants?

![Screen Shot 2020-02-20 at 11 14 11 AM](https://user-images.githubusercontent.com/2124049/74960536-20fe5d80-53d2-11ea-925b-f6db0326f74c.png)

**Comment by francisrupert** [comment]
@bignamehere,

Yeah, no reason each item (`class="fsa-timeline__item fsa-timeline__[VARIANT]"`) can't be used independent of its parent (`class="fsa-timeline"`), however unlikely it might be. 

While this component's documentation shouldn't _explicitly_ recommend it, the doc wording chosen should _implicitly_ suggest such a scenario is acceptable.

**Comment by bignamehere** [comment]
closing

**Comment by francisrupert** [comment]
@bignamehere Very nicely written doc.
