### ISSUE TITLE
Clarify Typographical Scale docs

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#303]
http://usda-fsa.github.io/fsa-design-system/visual-style/typography/index.html#typographical-scale

**Comment by bignamehere** [comment]
@francisrupert I updated the content to clarify when to use H element vs Text Size Utilities, and also fixed the broken links. I did some research, but could not figure out how to have the Markdown link directly to the named anchor though, so the links just take you to the Utilities page for now.
