### ISSUE TITLE
Correct aria-current 

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#307]
For each component using `aria-current` attribute, reflect the appropriate value as completed in https://github.com/USDA-FSA/fsa-style/issues/397

- [x] Stepped Tabs
- [x] Pagination
- [x] Content Tabs
- [x] Breadcrumb
- [ ] Any others?

**Comment by bignamehere** [comment]
I didn't find any others in the System that use it.
