### ISSUE TITLE
Breadcrumb: single item variation

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#308]
A single crumb item variation was added in https://github.com/USDA-FSA/fsa-style/issues/402

Include, and update [documentation](http://usda-fsa.github.io/fsa-design-system/components/breadcrumbs/). In particular, consider how its usage guidelines should be amended and discuss here if necessary.

**Comment by bignamehere** [comment]
@francisrupert it looks like there is an issue when using a single list item... I can't seem to figure out why.

A single list item coded like...
![Screen Shot 2020-04-09 at 11 52 27 AM](https://user-images.githubusercontent.com/2124049/78920182-9ee8f780-7a58-11ea-9918-d780eb3b46be.png)

produces...
![Screen Shot 2020-04-09 at 11 51 55 AM](https://user-images.githubusercontent.com/2124049/78920199-a5776f00-7a58-11ea-9c04-e6977f098691.png)

Looking at [402](https://github.com/USDA-FSA/fsa-style/issues/402) it seems like the CSS for `fsa-breadcrumb__item` should do everything needed. Is that feature not in 2.4.2?

Am I missing something?

**Comment by francisrupert** [comment]
@bignamehere,

My best guess is could be issue with build tooling, or `fsa-style` not current in `node_modules`, or something.

Confirm you see it at http://usda-fsa.github.io/fsa-style/#component__breadcrumbs.

**Comment by francisrupert** [comment]
@bignamehere,

Another note: I actually silently updated this repo to `fsa-style@2.4.2`, so you should see it in action at http://usda-fsa.github.io/fsa-design-system/components/breadcrumbs/.

Also confirm you've *pulled* `gh-pages` and `release/1.14.2`

**Comment by bignamehere** [comment]
@francisrupert yeah, I did a pulled release/1.14.2 before branching, but didn't pull gh-pages. Why would gh-pages need to be pulled for it to work, curious?

Also, package.json has 2.4.2 for fas-style listed, but I will try doing an npm install to see if it's out of sync.

**Comment by bignamehere** [comment]
@francisrupert found it... needed an `npm i` and `npm audit fix` to get it working.

**Comment by bignamehere** [comment]
added updates to release 1.14.2
