### ISSUE TITLE
Spacing Example Toggle

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#347]
Create script to toggle two images to appreciate before/after of Spacing Example for #344.
See screenshot for presumed location. 

![image](https://user-images.githubusercontent.com/1165933/84301729-e7389a80-ab19-11ea-9b9c-8c33b3d483df.png)

**Comment by francisrupert** [comment]
@bignamehere,

Since you're refactoring the Page Title toggle actions (#320), this feature falls under it as well. Can you fold this into your work on #320? I still have to actually update the image, but I'd love for this toggle to be available.

* Need not be cookied.
* Checked by default.
* I don't have an opinion if it would toggle the `img`'s `src` attribute, or merely show/hide between two images that are already on the page. I defer to you on that.`

**Comment by francisrupert** [comment]
@bignamehere,

Use branch `feature/347` available now on `origin`.

I've replaced the old PCP image with one from SPAR, `spacing-example.png` and provided the image to toggle between, `spacing-example--no-overlay.png`

**Comment by francisrupert** [comment]
@bignamehere,

Below is the before/after I'm thinking for this toggle. 

On (default) | Off
------------ | -------------
![asdf--after](https://user-images.githubusercontent.com/1165933/84678990-589b9300-aef6-11ea-81c9-9a76be649573.png) | ![asdf--before](https://user-images.githubusercontent.com/1165933/84679019-605b3780-aef6-11ea-925b-fa6fad5861b1.png)

**Comment by bignamehere** [comment]
@francisrupert pull down feature 347 branch and run it. Toggle is a new DS Component that allows for the use of a toggle and it will toggle the visibility/display any element within a DIV represented by the passed ID. 

See below for the config object that is passed.

```javascript
viewSpacing.init({
  toggleId: 'spacing-toggle-id',
  toggleHolderId: 'spacing-toggle-holder-id',
  holderClassPrefix: 'ds-docs-holder', // 'ds-docs-holder__on' or 'ds-docs-holder__off'
  isOnInit: false,
  useStorage: false
})
```

In the above code, we pass in the ID of the Checkbox (Toggle), the ID of the DIV that holds the items that will be toggled. Then we pass in the "holder class prefix" that is appended to the front of the class. eg.  `HOLDER-CLASS-PREFIX__on` and  `HOLDER-CLASS-PREFIX__off`

It also allows you to set the initial state of the Toggle, along with if you want to have that state be persistent (cookies).

You can have multiple toggles like this throughout the site, but each one needs a separate `ds-XYZ-toggle.js` file to be used with unique ID values.

let me know if you have any questions.

**Comment by francisrupert** [comment]
@bignamehere,

This is awesome. Perfectly abstracted out for additional use. I'll think on some other documentation use cases where to use it (and you should feel free to propose some too).

I only made one change: the script toggles `hidden` attribute rather than `style` properties to hide. You can diff that at commit 4f27da3b640c2758a21fcdd5735621cf40caa98f

I'll close this out and merge to `release/1.15.3`.
