### ISSUE TITLE
Quick Find Analytics

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#349]
### What

As a result of the Quick Find feature (#339), the Design System team would like to gain insight into its use.

### Task

Possibly paired with the findings of #69, identify a analytic-like method of tracking what destinations are followed **upon use of the Quick Find feature**.

**Comment by bignamehere** [comment]
@francisrupert I believe this will require a JS trigger to fire off a custom event. Looking at the GA data after I tested it yesterday, it doesn't look like there is a standard way to see what navigation control was the source of the navigation. A User could type "Components" in the Quick Find or they could click on the top nav, and GA wouldn't know the difference.

Adding a custom event will allow us to track the Usage of this feature. I will investigate if Google Tag Manager needs to be implemented along with the normal GA tracking code to enable custom events.

**Comment by bignamehere** [comment]
Link for referencde:  https://github.com/googleanalytics/autotrack

**Comment by bignamehere** [comment]
Added feature and it is currently tracking
