### ISSUE TITLE
Quick Find not working

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#399]
Assuming due to GA updates (#396...?) pushed since [Release 1.17.2](https://github.com/USDA-FSA/fsa-design-system/releases/tag/1.17.2).

**Comment by bignamehere** [comment]
@francisrupert It's working for me... can you specify what isn't working, and I will diagnose?

**Comment by bignamehere** [comment]
![image](https://user-images.githubusercontent.com/2124049/111197941-0d99d380-858d-11eb-9c87-0c04581cf887.png)

![image](https://user-images.githubusercontent.com/2124049/111197998-1be7ef80-858d-11eb-9681-4d6f39b2d5bc.png)

**Comment by francisrupert** [comment]
Sorry I wasn't specific. Selection of a suggestion doesn't navigate to destination, either by clicking or hitting return on arrowed-to selection.

**Comment by bignamehere** [comment]
When refactoring and breaking out the JS into separate object files, the call to GoogleTracker no longer included various methods, causing a JS error that prevented any propagation of the href. Tested and fixed.
