### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#44]
### Task

Create this repo's **Contributing.md**
### Details

Influenced by [USWDS' equivalent](https://raw.githubusercontent.com/18F/web-design-standards/18f-pages-staging/CONTRIBUTING.md)
### Progress
- [x] Drafting
  - [x] Add to "Getting Started" (#18)
- [x] Drafted
- [x] Reviewed

**Comment by brianmillsUX** [comment]
added draft (but edited!) page in "getting started" section - needs second reviewer

**Comment by francisrupert** [comment]
Moved to its own branch, `feature/license-and-contributing`, along with #43. Duplicate issue (intentionally) of https://github.com/USDA-FSA/fsa-style/issues/12
