### ISSUE TITLE
Icon Find - Categories Filter

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-design-system#448]
There is a need to add a filter to the Icon Finder tool (#413), based on the metadata provided by Google. Need to make sure the filter utilizes an appropriate control for the number of categories and the data remains dynamic and decoupled.

This issue also includes an update to the Grunt automation order.

**Comment by bignamehere** [comment]
@francisrupert I have updated the "Most Popular" category filter to perform a sort on the icon data based on the Google Popularity value, and when selected retrieve the top ranked X number of icons. The control mechanism has been switched from a hardcoded value within the JavaScript (previously a value in the thousands), to a data attribute in the HTML/template (`data-most-popular`). 

This allows for a more meaningful threshold for our team to control, and also removes any reliance on understanding or knowledge of Google's popularity value system... we just use the top ranked icons instead.

**Comment by francisrupert** [comment]
@bignamehere,

Jeez this is plain awesome. I pushed a few minor formatting tweaks on branch `issue/448`, pull those down and you'll see what I've done -- _partly_ associated with my comments below.

When I wondered about using the `popularity` field to identify "Most Common/Popular" at https://github.com/USDA-FSA/fsa-design-system/issues/454#issuecomment-875030206 I was thinking those would be what are _immediately previewed_ on load. Is that an easy adjustment?

**Comment by bignamehere** [comment]
@francisrupert  It would be a bit of reworking the code, but not a heavy lift. I think what might be best is to identify the "FPAC Default Set", which is what I thought the 143 that you have in the static example, and that are currently in [https://github.com/USDA-FSA/fsa-design-system/blob/issue/448/_data/fpac-material-icons-list.json](https://github.com/USDA-FSA/fsa-design-system/blob/issue/448/_data/fpac-material-icons-list.json). This JSON file is what controls what is shown to the User when the screen loads.

It is an independent set of icons that we can control, and does not User popularity at a dynamic control. So we can look at the top 143 or whatever number of the popular icons and use those to help us determine the Default FPAC set.

That or we can abandon our own controls (the above JSON list) and use Popularity to show the default loaded set. I just need to know if we want to retain the ability to show a specific Default set that is independent of Google's metadata.

thoughts?

**Comment by francisrupert** [comment]
Actually your point about a "Default set" is quite valid. Once I finally looked at the Top 49, it definitely warrants some selective editiing (e.g. something like "fingerprint" need not be surfaced to default set). 

The time invested in this remains extremely useful as we can use their most popular 50 or 100 or whatever to significantly **inform** what we can choose in `fpac-material-icons-list.json`.

I'd say we've got the whole Icon Search feature set solid enough to make official. Let's use #454 to initially update `fpac-material-icons-list.json` default set, which will likely grow or be refined over time anyhow.

What next steps and timing do you need to wrap up all of #413 and #448?

**Comment by bignamehere** [comment]
@francisrupert all sounds good on the Default set, and we can switch to #454 for that portion. As far as #413 and #448 these both are now fully tested and working properly. I can merge them into 1.18 today.

**Comment by francisrupert** [comment]
@bignamehere,

Awesome. Go for it. Branch `release/1.18.0` is up-to-date and ready for incoming merge.

**Comment by bignamehere** [comment]
merged into 1.18.0
