### ISSUE TITLE
Guides > Front-end

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#45]
### Task

Collect/author/edit **Front-end Guide**
### Details

Initially assigned to [Alpha Milestone](https://github.com/USDA-FSA/fsa-design-system/milestone/1), but may be de-prioritized to Post Alpha. _[EDIT, 10/03/2016: yep, moved to Icebox]_

Generally taking page out of https://pages.18f.gov/frontend/, with a focus on a Style Guide for HTML, CSS, and too a less degree JS. 
### Progress
- [ ] Outlined
- [ ] Drafting
- [ ] Drafted

**Comment by francisrupert** [comment]
Moving to Icebox. Completing this section isn't required for a true MVP state.

**Comment by bignamehere** [comment]
Closing issue as per 9e83eb8, but will continue to add sections thru new Issues.

**Comment by bignamehere** [comment]
closing
