### ISSUE TITLE
Default Icon Set

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#454]
The forthcoming Icon Set (#412, #413, and others on [this current Milestone](https://github.com/USDA-FSA/fsa-design-system/milestone/26)) makes available over 900 icons. 

A preliminary subjective listing of 147 icons are previewed prior to user's searching. These are meant to suggest "most commonly used". 

Revisit this listing and arrive at a listing that is 1. most relevant, and 2. of a reasonable amount (50? 25? 200?).

Depends on 

* #413 
* #448

**Comment by francisrupert** [comment]
@bignamehere,

In beginning this task ("most common icons") I noticed `MDOfficial.json` actually has a `"popularity"` field. Can we tap into that? 

That provides a quick (non-subjective) way to immediately preview the first 100 (or whatever amount) most common, and perhaps replicate their [Sort by Most Popularity | Name control](https://user-images.githubusercontent.com/1165933/124656568-fdbd3c80-de66-11eb-859d-43ea740da427.png).

If nothing else, it at least gives us an _objective_ listing to manually curate that previewed listing to a nice round number we (yes, subjectively) arrive at.

**Comment by bignamehere** [comment]
@francisrupert We have multiple ways to approach this, but the most important thing is to not be reliant on and external resource. This is why we have [our own list](https://github.com/USDA-FSA/fsa-design-system/blob/issue/413/_data/fpac-material-icons-list.json) that we have 100% control over, and it also allows us to utilize our own custom icons or non-Material Design icons if needed. We can certain use the metadata to come up with a preferred list, and I will look into that as "popularity" is a numeric value, not an assigned category.

There is consideration that needs to be taken when coding the solution, and determining if the Category Selection tool should is independent of the search part and vice versa. I would assume that the Category would be completely separate and display ALL icons in that category. The Category Selection should also be reset to the default value (no selection) when a search is performed, otherwise the assumption is the Search is performed within the Category set displayed.

What are your thoughts?

**Comment by francisrupert** [comment]
@bignamehere 

First, I agree with your instincts on Category selection combined with Search, and how you've described resetting Category upon search. Go with that and render judgment on best interaction. At this point, whatever blocks you the least, but still gets a good Find Icon capability.

As for your response to [my thoughts on taking advantage of `popularity` field](https://github.com/USDA-FSA/fsa-design-system/issues/454#issuecomment-875030206) I definitely wasn't thinking of permanently using it on an ongoing basis and relying too heavily on external resources. My thought was almost purely an initial way to arrive at a good starting point of "Most Common" from our perspective. My driving factor is removing most of the the _subjective_ by taking advantage of it as an objective starting point, and _then_ subjectively judge what's best.

Categories muddles things only a little bit for determining those Icons to initially preview. The top `n` amount spans all categories. So I figure pulling out the top 20 or so from each category, and then whittle them down manually to a nice manageable set we can curate as those to preview prior to manual search. If that's managed in `fpac-material-icons-list.json`, cool. If not, we at least are starting from a good qualitative angle.

In the interest of not blocking your work, would it actually be timelier for me to just eyeball the `popularity` values in `MDOfficial.json`, effectively achieving what I summarized in the third paragraph above?

**Comment by francisrupert** [comment]
**Outcome:**

To be manually curated on `fpac-material-icons-list.json` once merged in from...
* #413 
* #448

**Comment by bignamehere** [comment]
@francisrupert I’ve got a nice sneaky way to create the JSON for this, so I’ll take this one.

**Comment by francisrupert** [comment]
@bignamehere,

I spent a small amount of time refining the Default Set. Pull down `release/1.18.0` branch to see what I've done. I know you were working on a cleverer method to build that list, though I still wanted to make it more relevant than what we currently have.

I even added them in an order on `fpac-material-icons-list.json` that makes _some_ kind of sense, though the script reforms to alphabetical. It'd be nice to go by a custom order (screenshot below ).

Whatchathink? At the very least we could launch with this default list and update it at any time, including the auto-built list you were playing with.

![image](https://user-images.githubusercontent.com/1165933/126215023-584ac143-e98f-402e-941a-cb81771447be.png)

**Comment by bignamehere** [comment]
@francisrupert I previously made my [recommendations here](https://github.com/USDA-FSA/fsa-design-system/commit/41d3b4b46b26303c87bdc5eaa997f2dfa68ff9cd). They are based on the most popular listed by popularity with the removal of ones that don't seem relevant.

**Comment by francisrupert** [comment]
@bignamehere,

Very cool. Sorry I missed that. That's exactly what I was hoping for: an actual listing that gives us a data-driven starting point and still have the ability to customize from there.

I'll compare that against what I posted in my last comment, and manually merge what looks and feels relevant. And then of course we'll refine over time.

**Comment by bignamehere** [comment]
@francisrupert sounds good, and make sure you use this issues for updates to make it easier to compare code. The release 1.18.0 branch might have slightly different sorting code than this issue.

Lastly, we can sort the display by certain things, but initially it is ABC order... we can sort initially by popularity as well, or other data in the larger JSON file (all icons). It would be more difficult to sort the icons based on the order manually input in the FPAC default JSON file without a "key" code added to that data. The reason being is that order is not guaranteed without a "key" to sort properties of an object within JavaScript.

So the order in which you see the Icons should be based on a property value within the larger dataset.

**Comment by francisrupert** [comment]
@bignamehere,

I've updated `fpac-material-icons-list.json` on `issue/454`, and included a would-be `order` property for each. If the script were updated to enable customer order of _just_ this Default Set, it would resemble the below screenshot. 

No biggie at all if we don't get that implemented in for this release; not a priority, can always just update later as `1.18.1` or something.

![image](https://user-images.githubusercontent.com/1165933/126248843-f16f63f3-610f-4441-981b-97a5fdfbda0b.png)

**Comment by francisrupert** [comment]
@bignamehere,

Oop, I just now got that commit pushed, https://github.com/USDA-FSA/fsa-design-system/commit/3bc7d0d9093db619ebbc52b8c59330aa94e41252. Apparently it was failing through VPN.

**Comment by bignamehere** [comment]
@francisrupert I was wondering if I had something misconfigured! lol

**Comment by francisrupert** [comment]
@bignamehere,

Merge to `release/1.18.0` when able (or greenlight me to do so). This would close out the last subtask of #412. Targeting #461 Production COB!

**Comment by bignamehere** [comment]
merged and closing
