### ISSUE TITLE
Create category thumb previews

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#49]
Replace placeholder images for each page listed on Category layout. MVP version at least for Alpha release.
- [x] Components > [new component(s)]
- [x] Guides > Applications
- [x] Guides > Accessibility
- [x] Guides > Front-end
- [x] Guides > Content
- [x] Visual Style > Color
- [x] Visual Style > Typography
- [x] Visual Style > Size and Space
- [x] Visual Style > Grid and Responsive Breakpoints
- [x] Visual Style > CSS Utilities
- [x] Elements > Text Links
- [x] Elements > Buttons
- [x] Elements > Text Input
- [x] Elements > Textarea
- [x] Elements > Checkbox
- [x] Elements > Radio
- [x] Elements > Select
- [x] Elements > Tables

![image](https://cloud.githubusercontent.com/assets/1165933/17821068/503af27e-6615-11e6-9646-b429463c6b91.png)

**Comment by francisrupert** [comment]
@bignamehere,

I've assigned this to you as well. The images for each Component as they're added will be easy enough, it's the three **Guides** ones that are a headscratcher.

**Comment by bignamehere** [comment]
@francisrupert 

I realized last week as I went to do this, I don't have Adobe Illustrator or any other vector-based software. I sent an email last week to start the process to get it.

**Comment by francisrupert** [comment]
@bignamehere, Yeah, you should have received Brian's Illustrator and InDesign licenses. I assume you already have PS. If so, you can do some rudimentary vector work in there if needed for this task.

**Comment by bignamehere** [comment]
Added Thumbnails for Applications, Front-end, and Accessibility as per 9bdea6b

Content Thumbnail is still needed.

**Comment by bignamehere** [comment]
I added the last one (even without vector design tools).

Closing as per 0824276
