### ISSUE TITLE
Combine a11y Resources and Tools

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#65]
### Task

Combine `guides/accessibility/tools.md` and `guides/accessibility/resources.md` into single resource. There's some redundancy and no real reason to be separate.
### Steps
- [x] Organize their contents into a single page. Determine `title`, e.g. "Tools and Resources" or "Resources and Tools" or...? Use this as file name, i.e. `guides/accessibility/tools-and-resources.md`.
- [x] Update `_data/guide_accessibility.yml`, removing the current two and replacing with this combined one.

**Comment by brianmillsUX** [comment]
Closed issue as accessibility resources and tools content was combined on the "resources" page and the  accessibility menu was updated accordingly - thank you!
