### ISSUE TITLE
Design Principles

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#66]
### Task

Author **Design Principles** content for Design System.

Note: [high-level (to start)] content mainly detailing why and alluding to what/how.
### Progress
- [x] Drafting
- [ ] Drafted

**Comment by brianmillsUX** [comment]
Need to draft [high-level (to start)] FSA design principles primarily detailing why and alluding to what/how.

**Comment by brianmillsUX** [comment]
Task

Author Design Principles for Design System.

Progress

 Drafting
 Drafted

**Comment by francisrupert** [comment]
@brianmillsUX 

Think we can get this in the Alpha Milestone? I initially deprioritized it to [Icebox Milestone](https://github.com/USDA-FSA/fsa-design-system/issues?q=is%3Aopen+is%3Aissue+milestone%3AIcebox), but I suppose we can stretch-goal it for Alpha Milestone since it'd focus primarily on high-level to start with.

If you agree, go ahead and adjust the [Milestone](https://cloud.githubusercontent.com/assets/1165933/18173209/68c04790-702e-11e6-9e84-57db8175aa18.png) and change the Priority Label (from "P4").

**Comment by brianmillsUX** [comment]
We should strive for it - I have a draft I'll refine...beyond 18F and gov.uk also check out https://www.dto.gov.au

**Comment by francisrupert** [comment]
Cool. I've moved to [Alpha Milestone](https://github.com/USDA-FSA/fsa-design-system/issues?q=is%3Aopen+is%3Aissue+milestone%3AAlpha)
