### ISSUE TITLE
Guides > Editorial > Menu

### ISSUE THREAD

**Issue by brianmillsUX** [USDA-FSA/fsa-design-system#67]
### Task

Update **Menu** page listings/links for Editorial (formerly Content) Guide.
### Progress
- [x] Drafting
- [x] Drafted

**Comment by francisrupert** [comment]
@brianmillsUX,

If you're satisfied with the menu listing and order, go ahead and close this issue.

**Comment by brianmillsUX** [comment]
Looks great - thank you for your edits (big help)!
