### ISSUE TITLE
Starter Components

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#71]
## Question

What Starter Components should we make available?
## Thoughts
- The FSA Design System is **not meant** (at least any time soon) to be a comprehensive resource of a wide variety of HTML-based components.
- Only the most basic set of **extremely** common and/or obvious components would be made available here.

For example, we're shying away from making Header components available as we don't can't know what any given FSA site or app's header requirements are. Instead, designer/developer for any given FSA site or app would use the _style_ and basic _elements_ this makes available to build their own.
## Candidates
- Generic form structures
- Accordian
- Footer
- **Discuss below for possible candidates**

**Comment by brianmillsUX** [comment]
Agreed - initially offering high-level components that guide toward an accessible and responsive (perhaps even an adaptive) layout and focus on color and type over graphics may help folks get on the right track.

**Comment by francisrupert** [comment]
@jeremyhaas, here's the issue related to our morning conversation.

**Comment by francisrupert** [comment]
This high-level issue is specific to Design System repo, while issues for specific issues will be logged in [USDA-FSA/fsa-style/issues?label:component](https://github.com/USDA-FSA/fsa-style/issues?q=is%3Aissue+is%3Aopen+label%3Acomponent) -- starting with "Button Group", https://github.com/USDA-FSA/fsa-style/issues/137

**Comment by francisrupert** [comment]
Closing: effectively resolved by this starter list of components (though they have yet to be documented):

* #120 
* #118 
* #117 
* #114 
* #113 
* #112 
* #111 
* #110 
* #109
