### ISSUE TITLE
Create Action Items from 18F's Research Findings

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#75]
## Task

Create FSA-relevant action items gleaned from the 18F's [August Listening Tour Findings](https://github.com/18F/web-design-standards/wiki/August-Listening-Tour-Findings) and prioritize (across a would-be roadmap of milestones).
## Background

18F conducted a UX Research-ish "Listening Tour" with gov teams actively using the USWDS (led by 18F's UX Lead @bradnunnally, awesome job!). This week they published their [findings and recommendations](https://github.com/18F/web-design-standards/wiki/August-Listening-Tour-Findings).

We use USWDS as a major dependency and face a similar path to gaining adoption of the Design System within USDA-FSA dev ranks, and should make use of the insights gained from their research.
## Players
- @francisrupert (UX, Design, Front-end)
- @brianmillsUX (UX, Research, Content Strategy)
- @jeremyhaas (PM)

**Comment by brianmillsUX** [comment]
1000% agreed - we can even add our existing user insights/research as well as detail protocols and guidelines for UX research and UI prototyping...could even be another guide (and, in part, address some of what Johanna is interested in).
