### ISSUE TITLE
Create sample starter boilerplate-ish kit

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#80]
ala https://github.com/salesforce-ux/design-system-starter-kit/

Presumes a lot and is not a non-trivial task. Update this issue with further details and requirements. Sent to Icebox.

**Comment by francisrupert** [comment]
Source of inspiration: https://github.com/CastleCSS/castlecss-boilerplate

**Comment by bignamehere** [comment]
@francisrupert  would this Issue be completed with the development of the FSA Prototype Kit?
