### ISSUE TITLE
Draft sections introductions (MVP)

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#83]
- [x] Home
- [x] Visual Style
- [x] Elements
- [x] Guides

**Comment by francisrupert** [comment]
@bignamehere,

[Visual Style](http://usda-fsa.github.io/fsa-design-system/visual-style/) and [Components](http://usda-fsa.github.io/fsa-design-system/components/) each have some "intro" of some sort. The remaining action on this Issue is to come up with one for [Guides](http://usda-fsa.github.io/fsa-design-system/guides/)

**Comment by bignamehere** [comment]
closing as per 1a5cc43
