### ISSUE TITLE
Bad link to FSA Employee Responsibilities and Conduct

### ISSUE THREAD

**Issue by jeremyhaas** [USDA-FSA/fsa-design-system#94]
## Description

The link to the FSA EE Responsibilities and Conduct does not seem to find the appropriate source.  Source may have been moved.
## Steps to reproduce the issue
1. Opening a new issue
2. Click the link to view the Contributing Guidelines
3. Click the link in the 2nd paragraph
## screenshots

![image](https://cloud.githubusercontent.com/assets/18540541/19575506/6c1b16e6-96d4-11e6-921d-fbd6441f22b7.png)

![image](https://cloud.githubusercontent.com/assets/18540541/19575500/622d0f68-96d4-11e6-93fa-eab3e47602ec.png)

**Comment by francisrupert** [comment]
## Summary

@jeremyhaas, this issue addressed on @brianmillsUX's branch, viewable at [feature/brianedits/CONTRIBUTING.md](https://github.com/USDA-FSA/fsa-design-system/blob/feature/brianedits/CONTRIBUTING.md).

## Action Required
- @jeremyhaas: Review and approve as a direct comment below.
- @francisrupert: Upon approval merge branch and publish to gh-pages (Production), at which point this issue will closed.
- @brianmillsUX: Hi.

## Commit trail

This issue, #94, amended by commits https://github.com/USDA-FSA/fsa-design-system/commit/4dbc62856756d017e8d9769356368930900c0b38 and https://github.com/USDA-FSA/fsa-design-system/commit/1a2cb48e5ee1cba42d59394859814f9a2c516bf9

## Aside

@brianmillsUX, I saw you corrected the link on Thursday. I composed this response as if I were you, just as a further example of how at least the three of us can and should be using issues to communicate on action (commits) taken.

**Comment by brianmillsUX** [comment]
Thank you - I've been either in meetings or out of pocket since then. Now working on another ticket and then back to Playbook!

**Comment by jeremyhaas** [comment]
@francisrupert Approved!

**Comment by francisrupert** [comment]
Closed via 4dbc628 and 1a2cb48
